### PR TITLE
Support for inlining

### PR DESCRIPTION
**Pull request by mrange**
Left some thoughts and comments in the code.

### CODE REVIEW

**Comment by matthewcrews** [comment]
When I pull this down the compiler complains at line 7 saying it can't find a `Benchmark` class. Is there an additional file or reference that isn't included in here?

It also complains on line 230 saying the `BenchmarkConfig` is not defined. This is making me think there is another file defining a class that hasn't been included in this PR.

Am I missing something?

**Comment by mrange** [comment]
Yeah that was my mistake to test with PGO as well. I hope it works now.

**Comment by matthewcrews** [comment]
I've merged this and I'll be modifying it to make it flow better with the videos I'll be doing. I will be citing you though! 😊
I'm going to create a full video just cover the optimizations that this added.

**Comment by mrange** [comment]
Go ahead. You tell us on twitter when the video is out?

**Comment by matthewcrews** [comment]
Oh yes! First one will be out later today. Next one will likely be Thursday or Friday.

I'm changing the API around a little so the performance numbers change slightly but your approach is still the fastest 😊

**Pull request merged**
